- name: Set Node Exporter variables
  set_fact:
    node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    fallback_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-386.tar.gz"

- name: Try to download Node Exporter (primary URL)
  block:
    - name: Download Prometheus Node Exporter (primary)
      get_url:
        url: "{{ node_exporter_url }}"
        dest: "/tmp/node_exporter.tar.gz"
        timeout: 30
      register: download_result
      until: download_result is succeeded
      retries: 3
      delay: 10
  rescue:
    - name: Try to download Node Exporter (fallback URL)
      get_url:
        url: "{{ fallback_url }}"
        dest: "/tmp/node_exporter.tar.gz"
        timeout: 30
      register: fallback_download
      until: fallback_download is succeeded
      retries: 3
      delay: 5

- name: Verify download succeeded
  stat:
    path: "/tmp/node_exporter.tar.gz"
  register: download_stat

- name: Fail if Node Exporter download failed
  fail:
    msg: "Failed to download Node Exporter version {{ node_exporter_version }} from both primary and fallback URLs."
  when: not download_stat.stat.exists
