- name: Install Apache web server
  apt:
    name: apache2
    state: present
  become: yes

- name: Ensure Apache service is enabled and started
  service:
    name: apache2
    state: started
    enabled: yes

- name: Install git
  apt:
    name: git
    state: present
  become: yes

- name: Clone web app repo to /var/www/html
  git:
    repo: https://github.com/abel149/registration-and-grading-system
    dest: /var/www/html
  become: yes

- name: Set ownership to www-data
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes
  become: yes

- name: Set permissions on web app files
  file:
    path: /var/www/html
    mode: "0755"
    recurse: yes
  become: yes

- name: Restart Apache to apply changes
  service:
    name: apache2
    state: restarted
  become: yes
  notify: restart apache # if you already have this handler, else remove notify

- name: Deploy dynamic info page
  template:
    src: info.html.j2
    dest: /var/www/html/info.html

- name: Allow HTTP through ufw firewall
  ufw:
    rule: allow
    port: 80
    proto: tcp
