---
- name: Configure Web Servers
  hosts: webservers
  become: yes
  roles:
    - webserver

- name: Configure Database Servers
  hosts: dbservers
  become: yes
  roles:
    - database

- hosts: all
  become: yes
  roles:
    - webserver
    - database
    - monitoring
